Use numeric comparison

diff --git a/dnf-automatic-restart b/dnf-automatic-restart
--- a/dnf-automatic-restart
+++ b/dnf-automatic-restart
@@ -127,7 +127,7 @@ done
 
 tracer_out="$(tracer || {
   exit_code=$?
-  if [[ $exit_code > 0 && $exit_code < 100 ]]; then
+  if ((exit_code > 0 && exit_code < 100)); then
     >&2 printf 'Tracer failed with exit code %s\n' "$exit_code"
     exit $exit_code
   fi
@@ -145,9 +145,9 @@ daemon_reloaded=false
 
   printf 'Restarting service using %s\n' "$line"
   $line || {
-    exit_code=$?
-    if [[ $exit_code > 0 ]]; then
-      >&2 printf '%s failed with exit code %s\n' "$line" "$exit_code"
+    status=$?
+    if ((status > 0)); then
+      >&2 printf '%s failed with exit code %s\n' "$line" "$status"
     fi
   }
 
