Log and ignore failed restarts

diff --git a/dnf-automatic-restart b/dnf-automatic-restart
--- a/dnf-automatic-restart
+++ b/dnf-automatic-restart
@@ -135,7 +135,12 @@ tracer --services-only | tail --lines=+3 | while read -r line; do
   fi
 
   printf 'Restarting service using %s\n' "$line"
-  $line
+  $line || {
+    exit_code=$?
+    if [[ $exit_code > 0 ]]; then
+      >&2 printf '%s failed with exit code %s\n' "$line" "$exit_code"
+    fi
+  }
 
   if [[ "$line" == *firewalld* ]] && systemctl is-active --quiet docker; then
     echo 'Restarting docker because firewalld was restarted'
